--- /tmp/ffmpeg-4.1/libavcodec/Makefile
+++ /tmp/ffmpeg-4.1-src/libavcodec/Makefile
@@ -407,6 +407,7 @@
 OBJS-$(CONFIG_KGV1_DECODER)            += kgv1dec.o
 OBJS-$(CONFIG_KMVC_DECODER)            += kmvc.o
 OBJS-$(CONFIG_LAGARITH_DECODER)        += lagarith.o lagarithrac.o
+OBJS-$(CONFIG_LAGARITH_ENCODER)        += lagarith_enc.o
 OBJS-$(CONFIG_LJPEG_ENCODER)           += ljpegenc.o mjpegenc_common.o
 OBJS-$(CONFIG_LOCO_DECODER)            += loco.o
 OBJS-$(CONFIG_M101_DECODER)            += m101.o

